### ISSUE TITLE
GetDirectory of the Elements[0] : Server Error Error: invalid command 32

### ISSUE THREAD

**Issue by yboujraf** [dufourgilles/node-emberplus#5]
Dear @dufourgilles 

We have this error when :
- an equipment established a connection

**ember new connection from 172.11.11.2:52388
error: dropping frame of length 2 with invalid CRC**

- an equipment try to discover the tree (selecting manually the node to discover). The Elements[0] is ok but when requestion the getDirectory for the Qualifiednode, we have this error message.

Maybe is when we supported more Elements[]. Not sure.
In the sample test there is only one Elements[0] as describe it in the log from the server.

```
listening
server listening
**ember new connection from 172.11.11.2:52388
error: dropping frame of length 2 with invalid CRC**
ember new request from 172.11.11.2:52388 Root {
  elements: [
    Command { number: 32, fieldFlags: [EnumItem], _parent: [Circular] }
  ]
}
getDirectory response Root {
  elements: [ QualifiedNode { path: '0', contents: [NodeContents] } ]
}
ember new connection from 192.168.0.230:59844
ember new request from 172.11.11.2:52388 Root {
  elements: [
    Command { number: 32, fieldFlags: [EnumItem], _parent: [Circular] }
  ]
}
getDirectory response Root {
  elements: [ QualifiedNode { path: '0', contents: [NodeContents] } ]
}
ember new request from 172.11.11.2:52388 Root {
  elements: [
    Command { number: 32, fieldFlags: [EnumItem], _parent: [Circular] }
  ]
}
getDirectory response Root {
  elements: [ QualifiedNode { path: '0', contents: [NodeContents] } ]
}
**ember new request from 172.11.11.2:52388 Root { elements: [ Node { number: 0, children: [Array] } ] }
Server Error Error: invalid command 32
    at TreeServer.handleCommand (C:\Git\_EMBERPLUS\node-emberplus-master\server.js:458:32)
    at TreeServer.handleNode (C:\Git\_EMBERPLUS\node-emberplus-master\server.js:186:14)
    at TreeServer.handleRoot (C:\Git\_EMBERPLUS\node-emberplus-master\server.js:113:21)
    at S101Client.activeRequest (C:\Git\_EMBERPLUS\node-emberplus-master\server.js:35:37)
    at S101Client.makeRequest (C:\Git\_EMBERPLUS\node-emberplus-master\client.js:144:14)
    at S101Client.addRequest (C:\Git\_EMBERPLUS\node-emberplus-master\client.js:151:10)
    at S101Client.<anonymous> (C:\Git\_EMBERPLUS\node-emberplus-master\server.js:33:20)
    at S101Client.emit (events.js:209:13)
    at S101Codec.<anonymous> (C:\Git\_EMBERPLUS\node-emberplus-master\client.js:51:22)
    at S101Codec.emit (events.js:209:13)**
ember new request from 192.168.0.230:59844 Root {
  elements: [ QualifiedParameter { path: '0.1.0', children: [Array] } ]
}
unsubscribe
ember new request from 192.168.0.230:59844 Root {
  elements: [ QualifiedParameter { path: '0.1', children: [Array] } ]
}
unsubscribe
ember new request from 192.168.0.230:59844 Root {
  elements: [ QualifiedParameter { path: '0.2', children: [Array] } ]
}
unsubscribe
ember new request from 192.168.0.230:59844 Root {
  elements: [ QualifiedParameter { path: '0.0', children: [Array] } ]
}
unsubscribe
```

Best Regards
Youssef

**Comment by dufourgilles** [comment]
Fixed
